### ISSUE TITLE
status update?

### ISSUE THREAD

**Issue by araid** [Hebali/ciFaceTracker#1]
Hi, I'm just curious in what state this block is. 
- What version of Cinder was it built for?
- Is there any sample for it? 
- Is it worth trying to update it to glNext or should I try to port Kyle's again, since there have been some updates in his code?

Any general tips are welcome.

**Comment by Hebali** [comment]
Hi, This block is very out of date. I haven't used it myself in quite awhile. If there's still interest, a glNext update sounds good. I don't have time to spearhead that at the moment, but happy to help.

**Comment by couleurs** [comment]
hey araid, did you end up working more on this?

**Comment by araid** [comment]
No, I ended up going with a paid solution :)

But Kyle Mcdonald's block is pretty up to date and shouldn't be too hard to port https://github.com/kylemcdonald/ofxFaceTracker

**Comment by vinjn** [comment]
I have a custom build that works with latest Cinder.
https://github.com/OpenAVR/FaceVFX/tree/master/src/IFaceTracker
